### PR TITLE
Fix DISTANCE description and BNF grammar.

### LINKED ISSUE #28: Fix `DISTANCE` description
Markus Demleitner raised the point that the 2-arguments version of `DISTANCE()` allowed 2 general geometries instead of 2 points. Computing the distance between 2 points is easy but between 2 geometries requires an clear explanation of how such distance is computed.

To paraphrase Markus:

> Being general here is a pain in the neck (actually, that's why I ran
into this question).  For one, you'll need to define distance
much more carefully for such geometries, and if (as I think we ought
to) we chose "minimum of distances of between all points in arg 1 and
arg 2", I doubt we'll see many correct implementations of that.  Also
I'll want to map a lot of DISTANCE calls into contains(point,
circle) statements (because that's much easier on the query planner),
and that's a pain if one of the points could actually be, say, a
polygon.

The issue here is about limiting the 2 arguments of `DISTANCE()` to be POINTs.

_Complete email thread on <http://mail.ivoa.net/pipermail/dal/2020-February/008268.html>_

### PR DESCRIPTION
**Pull request by gmantele**
Fixes #28

### CODE REVIEW

**Review by msdemlei — APPROVED** [review]
Fixes my concerns -- thanks.

**Comment by gmantele** [comment]
_Ho, it seems that only the approval of a reviewer with write access is required in there. I did not know that. Anyway, having approval of other collaborators is still very useful and meaninful to have. So, thanks @msdemlei for your review :-)_

**Review by molinaro-m — APPROVED** [review]
I approve this fix for issue #30

**Comment by molinaro-m** [comment]
@gmantele feel free to merge

**Pull request merged**
