### PR TITLE
DOUBLE and PRECISION are SQL, not ADQL reserved words

### PR DESCRIPTION
**Pull request by mbtaylor**
DOUBLE and PRECISION are now entries in the list of SQL reserved words not ADQL reserved words as included in both the Section 2 text and the BNF, as they were in ADQL 2.0 (I believe they are both SQL92 reserved words).

The main reason for this change was to remove the item "DOUBLE PRECISION" from the "CAST: function and datatypes" sublist in the ADQL reserved keywords section 2.1.4 of the text, on the grounds that an item with embedded whitespace doesn't look right in a list of tokens.

### CODE REVIEW

**Comment by gmantele** [comment]
Thanks @mbtaylor :-)

All of this seems OK to me. As I said, I do not merge it now. I want to review other keywords potentially in the same situation. I'll do that next week.

**Comment by gmantele** [comment]
@mbtaylor just for information, I published the commits I wanted to add to this PullRequest in your repository as another PullRequest ; see mbtaylor/ADQL/pull/1

**Comment by mbtaylor** [comment]
@gmantele  thanks for the notification; since you weren't able to push your commits onto my PR branch, and I didn't get an auto-notification that you had submitted a PR to that branch, it looks like there are at least two bits of configuration I need to sort out...

**Review by gmantele — APPROVED** [review]
Thanks @mbtaylor for merging my commits :)

**Comment by gmantele** [comment]
> @gmantele thanks for the notification; since you weren't able to push your commits onto my PR branch, and I didn't get an auto-notification that you had submitted a PR to that branch, it looks like there are at least two bits of configuration I need to sort out...

No problem. I wrote this comment exactly because I suspected you did not get any notification :)

**Pull request merged**
