### PR TITLE
Add a recommendation to data providers about case folding.

### LINKED ISSUE #47: Add a note about case folding of identifiers
With different implementations of ADQL/TAP come different behaviours regarding the case folding of table/column identifiers.

For instance, let's take a column named `ra`. In different implementations, it could be defined with a different case. Multiple reasons could lead to a such situation: different DBMS, different service implementers choice, different ADQL parser, ... Because of that, the theoretically same ADQL query may not work in all these implementations. In one ADQL service the following will work:

```sql
SELECT ra
FROM a_great_table
```

...but will not in the second unless the column identifier is written with a different case and between double quotes:

```sql
SELECT "Ra"
FROM a_great_table
```

Besides, some ADQL parsers will consider that a non-delimited column (or, generally speaking, an identifier) will match an existing column whatever case it is written in. Other parsers will not. _Note that all have to preserve the case when the identifier is delimited (i.e. put between double quotes)._

Because of such differences in the processing of case folding when specifying identifiers (i.e. columns, tables, schemas), some users can easily be confused. However, this situation is really hard to fix as most implementations depend on DBMS that already have different behaviours regarding case folding of identifiers.

In order to make ADQL users aware of this but also to make ADQL implementers more careful on their choice of identifiers, a note should be added in the ADQL standard document.

One suggestion raised by @msdemlei on the DAL mailing list ([8th Dec. 2020 - "TAP, ADQL and field names inconsistencies between providers."](http://mail.ivoa.net/pipermail/dal/2020-December/008395.html)) is:

> a word of advice:
> avoid mixed-case names in ADQL databases; they become trouble as soon
> as people start gratuitously adding quotes to identifiers, which at
> least a certain demography is likely to do

### PR DESCRIPTION
**Pull request by gmantele**
The idea of this PR is to propose a comment aiming data providers about case folding. Ideally identifiers should not be declared using delimited identifiers.

Fixes #47

### CODE REVIEW

**Comment by msdemlei** [comment]
On Wed, Feb 17, 2021 at 05:55:58AM -0800, Grégory Mantelet wrote:
> The idea of this PR is to propose a comment aiming data providers
> about case folding. Ideally identifiers should not be declared
> using delimited identifiers.

Thanks for writing this, and you'd have my blessing as-is.

However, I consider "user experience" one of these business bs words.
And I claim any text worth writing can immediately be improved by
taking such words out.

It seems to me that's the case here, too: you're giving actual and
valid reasons for why people shouldn't use delimited identifiers
further down, so nothing at all is lost if you discard the "For a
better <bs elided>" and just start with "Data providers should".

**Comment by gmantele** [comment]
> However, I consider "user experience" one of these business bs words. And I claim any text worth writing can immediately be improved by taking such words out.

I actually used these words to introduce the following recommendation quickly with different words (rather than a "long" explanation)....so, more as a transition effect than with a "business" aim (either no bs really intended from myself).

In brief, I remove these "offending" words.

**Comment by msdemlei** [comment]
On Wed, Feb 17, 2021 at 06:55:16AM -0800, Grégory Mantelet wrote:
> > However, I consider "user experience" one of these business bs
> > words. And I claim any text worth writing can immediately be
> > improved by taking such words out.
> 
> I actually used these words to introduce the following
> recommendation quickly with different words (rather than a "long"
> explanation)....so, more as a transition effect than with a
> "business" aim (either no bs really intended from myself).

Oops -- re-reading this I notice I sounded a lot harsher than was
appropriate.  The comment really didn't communicate the smile I had
on my face when I wrote that comment.

Apologies if I've offended you -- but thanks nevertheless for taking
out the UX language.

**Comment by gmantele** [comment]
Don't worry...I totally pictured you saying that (with a mischievous/malicious smile) ;-P

**Review by molinaro-m — APPROVED** [review]
Provided, cleaned up text, looks good to me.
Not sure whether @msdemlei should give the approval, but it's fine, for me to merge this.

**Pull request merged**
