### PR TITLE
Updating role diagram and architecture section.

### PR DESCRIPTION
**Pull request by msdemlei**
Versus the old PNG, I am removing STC and SimDM, which seem a bit whimsical in there.

Also, I am introducing the ivoid of ADQL 2.1 for the purposes of TAPRegExt in here.

### CODE REVIEW

**Comment by gmantele** [comment]
Funny, I was going to update the role diagram too ^^

Because we reference a lot of things from DALI, I thought to include it also in there. But maybe it is not supposed to be in this way, but the other way around: the role diagram of DALI including ADQL. I do not know.

Maybe also STC-s should still be in this diagram as it is mentioned as acceptable geometry and coordinate system format.

**Comment by gmantele** [comment]
I agree to remove SimDM.

I rather keep STC-s in the role diagram as long as we reference it in this document for region and coordinate system definition. Or maybe, if possible, put a STC box in light color and/or with a dashed border (I don't really know what is possible to do).

DALI also seems to have a place in this diagram because we use it for datatypes and their serialization (e.g. POINT, CIRCLE, TIMESTAMP, INTERVAL).

That's all I can think about. I don't think there is another standard using/mentioning ADQL for the moment or on which ADQL relies on.

As I said, I don't now what really should be on this diagram: standards used by the current document, or standards using the current standard. Maybe both?

**Comment by gmantele** [comment]
Thanks for the addition of DALI :)

**Comment by msdemlei** [comment]
On Mon, Mar 27, 2023 at 02:43:10AM -0700, Grégory Mantelet wrote:
> Because we reference a lot of things from DALI, I thought to
> include it also in there. But maybe it is not supposed to be in
> this way, but the other way around: the role diagram of DALI
> including ADQL. I do not know.

Aw, you're right -- DALI is an important relationship, actually in
both directions, even though we don't really depend too much on what
DALI is most concerned about, the VOTable serialisation of our result
sets.  But in particular because ADQL 2.0 contained some... let me
say not terribly well engineered, rules on geometry serialisation and
DALI allows us to not have to worry about them, it's clear we have to
mention it.

> Maybe also STC-s should still be in this diagram as it is mentioned
> as acceptable geometry and coordinate system format.

Alas, the S-acronym!  The trouble is that there is no STC-S REC we
could reference, and I sure hope there won't be one.  There is the
appendix on TAP, and perhaps one day DALI will have something to say
about it -- and both of these we now already mention.

**Review by gmantele — APPROVED** [review]

**Pull request merged**
