### PR TITLE
Add a note about the the UDF catalogue

### PR DESCRIPTION
**Pull request by gmantele**
Add a recommendation to use UDFs listed in the PEN about a UDF catalogue
(Campillo and Demleitner, 2019 -
<http://www.ivoa.net/documents/udf-catalogue/index.html>).

This commit is a first attempt to fix issue #16

### CODE REVIEW

**Comment by gmantele** [comment]
I have added a new command in `ivoa-cite.tex` named `\CatalogUDF` which cite the PEN about the UDFs catalogue. However, there is no reference to this document in the repository `ivoatex` and more precisely in the file `ivoabib.bib`.

Is it because it is still a _Proposed_ Endorsed Note, or just because it is an Endorsed Note?
Or is it just because this file is not up to date? If it is the case, how to update it? Am I allowed to?

**Comment by gmantele** [comment]
I added the following lines in my local `ivoabib.bib`:

```
@Misc{note:UDFCatalogue,
  author =       {Jon Juaristi Campillo and Markus Demleitner},
  title =        {Catalogue of {ADQL} User Defined Functions},
  howpublished = {{IVOA Note}},
  year =         {2019},
  month =        {September},
  url =          {http://www.ivoa.net/documents/udf-catalogue/index.html}
}
```

**Comment by jontxu** [comment]
> Add a recommendation to use UDFs listed in the PEN about a UDF catalogue
> (Campillo and Demleitner, 2019 -
> http://www.ivoa.net/documents/udf-catalogue/index.html).

It should be Juaristi Campillo in any case. Both are surnames.

**Comment by gmantele** [comment]
> It should be Juaristi Campillo in any case. Both are surnames.

Sorry for this mistake in your name. It is present only in my above comment which is also the commit description. Not sure I can fix the commit message that easily right now (without a `push --force`), but I will do it just before/after merging the PR.

However, in order to avoid this mistake in the ADQL document, I admit having no idea. It is automatically generated from the file `ivoabib.bib` where, as you can see above, I wrote all your first- and surnames. Maybe the person(s) who will tell me how this file can be updated will know how to fix that. Personally, I am really far from being a LaTeX expert :(

**Comment by msdemlei** [comment]
> I have added a new command in `ivoa-cite.tex` named `\CatalogUDF` which cite the PEN about the UDFs catalogue. However, there is no reference to this document in the repository `ivoatex` and more precisely in the file `ivoabib.bib`.
> 
> Is it because it is still a _Proposed_ Endorsed Note, or just because it is an Endorsed Note?
> Or is it just because this file is not up to date? If it is the case, how to update it? Am I allowed to?

Endorsed notes will be in ADS and then eventually in docrepo.bib.

As to who updates that... Well, on volute it was mostly me, when I chanced upon it, but really everyone could (type make docrepo.bib in ivoatex).

With the elaborate access control, possibly requiring branching and merging, that's planned for github... I frankly don't know.  I could see volunteering for it, perhaps.

**Comment by msdemlei** [comment]
> I added the following lines in my local `ivoabib.bib`:
> 
> ```
> @Misc{note:UDFCatalogue,
>   author =       {Jon Juaristi Campillo and Markus Demleitner},

Make Jon's name "Jon {Juaritsti Campillo}", and BibTeX will do the right thing.

**Comment by gmantele** [comment]
> > I added the following lines in my local `ivoabib.bib`:
> > ```
> > @Misc{note:UDFCatalogue,
> >   author =       {Jon Juaristi Campillo and Markus Demleitner},
> > ```
> 
> Make Jon's name "Jon {Juaritsti Campillo}", and BibTeX will do the right thing.

It works. Thanks.

**Comment by gmantele** [comment]
> Endorsed notes will be in ADS and then eventually in docrepo.bib.
> 
> As to who updates that... Well, on volute it was mostly me, when I chanced upon it, but really everyone could (type make docrepo.bib in ivoatex).

This command erased the document `docrepo.bib`. There seems to be an error while querying ADS (I think they changed their API recently). Anyway, this Endorsed Note is not yet in ADS ; probably because it is still in _Proposed_ state.

Any plan to update its status?
Should we wait for this to be updated before releasing ADQL-2.1?

**Comment by msdemlei** [comment]
> Any plan to update its status?
> Should we wait for this to be updated before releasing ADQL-2.1?

No, we shouldn't wait.  If ADQL 2.1 is ready, just put the note bibtex into a local.bib as per ivoatexDoc and be done with it.

However, given there's only three people left I have to get going for getting the UDF cat endorsed, I'd say there's an excellent chance we'll have it in docrepo.bib before you have to hand in ADQL 2.1's REC.

**Comment by gmantele** [comment]
I agree. I am quite confidente that the Endorsed Note will be ready before ADQL-2.1 goes REC.
So, for me, we can already merge this PullRequest....unless you, @msdemlei, say there is still something to do here to "enable the bibtext connection" correctly when the EN will be ready? I admit, I am really not familiar at all with all these latex/bibtex things :S

**Comment by msdemlei** [comment]
On Fri, Oct 23, 2020 at 02:43:15AM -0700, Grégory Mantelet wrote:
> I agree. I am quite confidente that the Endorsed Note will be ready before ADQL-2.1 goes REC.
> So, for me, we can already merge this PullRequest....unless you, @msdemlei, say there is still something to do here to "enable the bibtext connection" correctly when the EN will be ready? I admit, I am really not familiar at all with all these latex/bibtex things :S

We can't really guess the bibcode this will get now, so there's nothing
we can do at this point except have TODO as the ref target.  That
way, we'll at least notice it at submission time (if the submitter
follows the submission checklist
https://ivoa.net/documents/Notes/IVOATex/20180814/NOTE-ivoatexDoc-1.2-20180814.html#tth_sEc3.11,
that is...).

Hence, let's go.

**Comment by gmantele** [comment]
Ok. Thank you for the info.

So, instead of writing a TODO in the doc, I would prefer to keep this PullRequest open until that time. In that way, no risk to forget about it as this PullRequest and corresponding Issue will still be visibly open.

**Comment by gmantele** [comment]
Now that the Catalogue UDF note is a PEN, I think it should be now possible to complete this PullRequest. @msdemlei do you know how I can now reference this note properly? I tried `make docrepo.bib' on my side, but still get an error, and I admit I don't really get how this works. Should not it be updated in the GitHub repo ivoatex directly (and then I update my sub-project pointing to to ivoatex)? If so, I don't see this note in the file [docrepo.bib](https://github.com/ivoa-std/ivoatex/blob/master/docrepo.bib) of this repo.

**Comment by msdemlei** [comment]
On Fri, May 14, 2021 at 09:55:48AM -0700, Grégory Mantelet wrote:
> Now that the Catalogue UDF note is a PEN, I think it should be now
> possible to complete this PullRequest. @msdemlei do you know how I
> can now reference this note properly? I tried `make docrepo.bib' on

It's 2021ivoa.spec.0310C once ivoatex PR #52
(https://github.com/ivoa-std/ivoatex/pull/52) is merged (feel free to
approve...) and you've run make update in the ADQL spec (provided the
existing ivoatex is new enough; otherwise, it's git submodule update
--remote).

> my side, but still get an error, and I admit I don't really get how

Could you paste the error in a bug against ivoatex?

**Comment by gmantele** [comment]
Thank you @msdemlei  (sorry, I have not seen your message before today). It now works as expected :sunglasses: 

So, if everything is fine for everybody, I think we can now _finally_ merge and close this PullRequest.

**Review by molinaro-m — APPROVED** [review]
Everything looks OK to me.

**Pull request merged**
