### PR TITLE
Fix issues #6 and #7 - Add README and LICENSE files.

### PR DESCRIPTION
**Pull request by gmantele**
2 files added:

- `README.md`:
  - describe very briefly the ADQL standard.
  - the last stable version (REC-2.0 now) and the current version (PR-2.1 now) are specified,
  - tell how to collaborate
  - add license information + GitHub badge
  - add a GitHub badge showing the current status/version of the repository
- `LICENSE.txt`: Creative Commons BY-SA 4.0

### CODE REVIEW

**Comment by gmantele** [comment]
_(cf issues #6 and #7)_

**Review by Zarquan — COMMENTED** [review]
In the how to contribute part, should we ask users to create a branch in their fork ? That was what was in the slides that James presented at the interop.
https://wiki.ivoa.net/internal/IVOA/InterOpOct2019GitHub/IVOA_Github.pdf?page=6

**Comment by gmantele** [comment]
> In the how to contribute part, should we ask users to create a branch in their fork ? That was what was in the slides that James presented at the interop.
> https://wiki.ivoa.net/internal/IVOA/InterOpOct2019GitHub/IVOA_Github.pdf?page=6

README fixed.

I have also added the link toward the slides of James ; later, this may be removed or replaced by an IVOA document if there is one describing this process.

**Review by Zarquan — APPROVED** [review]
Looks good :-)

**Pull request merged**
