### PR TITLE
Update GitHub Workflows with PDF preview

### PR DESCRIPTION
**Pull request by gmantele**
This PullRequest is in 2 parts:

1. Extend the existing GH-Workflow (build.yml) so that it also update the same Pre-Release item ("Auto PDF Preview") with a PDF Preview of the last merged commit. The idea is to have a static URL toward a PDF preview....this URL will ideally be accessible in the README.md file (see next PR). _This Pre-Release must never be published ; it also aims to give an automatically updated preview of the IVOA document._

2. Add a new Workflow (release.yml) triggered when a tag started with 'v' (e.g. `v2.1`, `v3.0`) is created on a commit. Then a new GitHub Release is created with the corresponding PDF version. This Release item will have to be edited afterward to add a clear human title and description, and eventually change the PDF file name (e.g. from `ADQL.pdf` to `REC-ADQL-2.1-....pdf`).

### CODE REVIEW

**Comment by gmantele** [comment]
Apparently some permissions to the special user 'github-actions' are missing:

```
> Move the auto-pdf-preview tag
[...]
Setting up git machine...
Forcing tag update...
Forcing tag push...
remote: Permission to ivoa-std/ADQL.git denied to github-actions[bot].
```

No idea how to solve this or how to use another user with the right permissions...

**Comment by jd-au** [comment]
> Apparently some permissions to the special user 'github-actions' are missing:
> 
> ```
> > Move the auto-pdf-preview tag
> [...]
> Setting up git machine...
> Forcing tag update...
> Forcing tag push...
> remote: Permission to ivoa-std/ADQL.git denied to github-actions[bot].
> ```
> 
> No idea how to solve this or how to use another user with the right permissions...

It looks like the PR does not have permissions to update the repository tags. That seems to me to be a reasonable restriction - otherwise anyone could make arbitrary updates to the repo with a malicious PR. Can you avoid the need to do the tagging? Could the initial release be created manually and then the script just drops the release in there?

**Comment by msdemlei** [comment]
On Mon, May 11, 2020 at 03:47:21AM -0700, Grégory Mantelet wrote:
> 1. Extend the existing GH-Workflow (build.yml) so that it also
> update the same Pre-Release item (&quot;Auto PDF Preview&quot;)
> with a PDF Preview of the last merged commit. The idea is to have a
> static URL toward a PDF preview....this URL will ideally be
> accessible in the README.md file (see next PR). _This Pre-Release
> must never be published ; it also aims to give an automatically
> updated preview of the IVOA document._

I'm not sure whether you're being over-protective there -- I think
the risk of such documents getting out of hand isn't so high, and of
course there's still the status declaration.

> 2. Add a new Workflow (release.yml) triggered when a tag started
> with &#39;v&#39; (e.g. `v2.1`, `v3.0`) is created on a commit. Then
> a new GitHub Release is created with the corresponding PDF version.
> This Release item will have to be edited afterward to add a clear
> human title and description, and eventually change the PDF file
> name (e.g. from `ADQL.pdf` to `REC-ADQL-2.1-....pdf`).

I'm *really* skeptical of that.  Releases are a rare thing; there's
quite a bit more to be done to them that you don't want in CI -- see
http://ivoa.net/documents/Notes/IVOATex/20180814/NOTE-ivoatexDoc-1.2-20180814.html#tth_sEc3.11

I'd say it ought to be up to the editors (or some person designated by
them) to prepare releases.

**Comment by gmantele** [comment]
> Can you avoid the need to do the tagging? Could the initial release be created manually and then the script just drops the release in there?

Actually, tagging is required to make a non-draft release. And the problem with draft releases is that they do not have a unique identifier and so, no unique URL. That's why I am creating a pre-release and that I need to create a tag.

This tag also needs to move to the last commit each time because otherwise we would have a pre-release with an up-to-date PDF preview, but an incorrect link to the history and so, with incorrect zip and tar balls (containing all the sources at the tagged commit). I think it is better to keep consistency.

Honnestly, I do not think it is wrong to allow github-actions to move this tag. However, maybe the action to generate the PDF should not be done at PR creation as it has just been done. I did not think it would do so. I thought it would run this action at the moment the PR is merged with the repository...and I think it would be better. And in such case, github-actions should be allowed to move tag and create/update a release....or we have to find another way to publish a PDF preview automatically....

**Comment by gmantele** [comment]
> I'm not sure whether you're being over-protective there -- I think the risk of such documents getting out of hand isn't so high, and of course there's still the status declaration.

Do you speak about the fact that the "pre-release" should stay a "pre-release"?
If yes, it is due to the fact that the workflow action will overwrite all the time the same release (so any manual modification of the release will be automatically overwritten by GitHub each time a PR is merged), but also to the fact that this PDF version is not a "final" version in the IVOA sense (neither a Proposed Recommendation nor a Recommendation), so there is no way it should be considered as a Release ; in that sense, it should considered as a draft or pre-release. But well, I admit even if it is stated as a Release instead, its title is pretty clear that it does correspond to an IVOA final version (REC or PR)....so there is not much harm here....so maybe a bit over-protective, but it was just to make clear that it should not be considered as a stable version.

**Comment by gmantele** [comment]
> I'm *really* skeptical of that. Releases are a rare thing; there's quite a bit more to be done to them that you don't want in CI -- see http://ivoa.net/documents/Notes/IVOATex/20180814/NOTE-ivoatexDoc-1.2-20180814.html#tth_sEc3.11 I'd say it ought to be up to the editors (or some person designated by them) to prepare releases.

Not sure to understand exactly what you mean here, but if you say that the GitHub workflow should not start preparing the release going along with a new 'v*' tag creation, fine with me. It was just to help by already generating the PDF....so that the editor(s) would just have to create the tag and then write the title
and description...no need to upload the PDF. It was quite easy to already prepare that, but it is very optional. So, if nobody thinks it is really useful, I can drop it from this PR.

**Comment by gmantele** [comment]
What do you think of the following suggested modifs?

- `build.yml` stays the same as before this PR (build the PDF + check it + keep it only as an artefact in the build job) ; it is triggered when a PR is created/edited

- `preview.yml` is a new workflow which create the PDF preview and update the same (pre-)release ; it is triggered only when commits are pushed to master (so, exactly at the time the PR is merged with the repository)

- _(eventually `release.yml` in function of what your answers to my previous messages will be)_

But of course, for `preview.yml` we still need to find a way to manage the only tag and the only release we have to update.

**Comment by msdemlei** [comment]
On Mon, May 11, 2020 at 06:34:55AM -0700, Grégory Mantelet wrote:
> > I'm *really* skeptical of that. Releases are a rare thing;
> > there's quite a bit more to be done to them that you don't want
> > in CI -- see
> > http://ivoa.net/documents/Notes/IVOATex/20180814/NOTE-ivoatexDoc-1.2-20180814.html#tth_sEc3.11
> > I'd say it ought to be up to the editors (or some person
> > designated by them) to prepare releases.
> 
> Not sure to understand exactly what you mean here, but if you say
> that the GitHub workflow should not start preparing the release
> going along with a new 'v*' tag creation, fine with me. It was just
> to help by already generating the PDF....so that the editor(s)
> would just have to create the tag and then write the title
> and description...no need to upload the PDF. It was quite easy to
> already prepare that, but it is very optional. So, if nobody thinks
> it is really useful, I can drop it from this PR.

My point is that github shouldn't be part of the relase process, as
there's quite a bit more that's involved than just making the PDF
(actually, HTML generation is quite a bit more fragile).  And there
shouldn't be any PDFs on github that people might be tempted to link
to at all -- if you link IVOA PDFs outside of document development,
only do it from the IVOA page, or we'll end up being horribly
confused.

So: I'm all for generating PDFs for a PRs, and ideally those will
disappear when the PR disappears.  I don't think CI should ever
exfiltrate built PDFs on master, regardless of the existence of tags;
given the platform habit so many people have these days, the risk
that these will be used instead of what's on ivoa.net is too high.

**Comment by gmantele** [comment]
> My point is that github shouldn't be part of the relase process, as there's quite a bit more that's involved than just making the PDF (actually, HTML generation is quite a bit more fragile). And there shouldn't be any PDFs on github that people might be tempted to link to at all -- if you link IVOA PDFs outside of document development, only do it from the IVOA page, or we'll end up being horribly confused.

Agreed. Let's keep the current IVOA process to release IVOA document.
So, ok, I'll remove `release.yml`.

> So: I'm all for generating PDFs for a PRs, and ideally those will disappear when the PR disappears. I don't think CI should ever exfiltrate built PDFs on master, regardless of the existence of tags; given the platform habit so many people have these days, the risk that these will be used instead of what's on ivoa.net is too high.

The PDF generated with `preview.yml` would not be only for PR, but for the current version on master. That's why I speak about preview and pre-release.

The whole idea of this PDF preview is to offer a readable view of an in-progress IVOA document so that making easier the exchanges in Issues and Pull-Requests. Some (most?) users complain about the difficulty to interact because they can not see the document, unless they have enough technical skills and/or time to use GitHub commands, the Makefile and the LaTeX installation. The other alternative, as you say, is to wait for a PDF version available on the IVOA page...and that does not happen each time the document is modified.

What I propose is just to have a preview link in the README.md page. But to have this link, I need a static URL. And the only way to get one is to use this mechanism of pre-release. I made such link on my fork of ADQL:

- [Link of the PDF Preview at the top of the README.md](https://github.com/gmantele/ADQL/blob/ci-update-release-with-pdf/README.md)
- [Releases' page](https://github.com/gmantele/ADQL/releases)

**Comment by jd-au** [comment]
@gmantele I'm happy with your proposed revised approach of this PR just adding a pre-release PDF and an associated tag on merging PRs. There is a lot of demand for a PDF showing the current state of the document  and it dramatically increases the accessibility of the repository for feedback from wider groups, as well as the transparency. Taking on board Markus' concerns I think we should make sure the PDF is very obviously labelled as a preview draft, probably as a watermark. Unless it is already supported, adding a watermark might be something more for the ivoatex build process though so is outside the scope of this PR.

**Comment by msdemlei** [comment]
On Mon, May 11, 2020 at 09:07:12AM -0700, Grégory Mantelet wrote:
> The whole idea of this PDF preview is to offer a readable view of
> an in-progress IVOA document so that making easier the exchanges in
> Issues and Pull-Requests. Some (most?) users complain about the

So, the idea would be that people can look at the PDF of master as a
reference for the PR?  Hmwell, I guess that's fair enough.  So, I
retract my concerns about building on master.

I like James' idea of (some sort of) a watermark for that purpose.  I
think a true watermark is too high-tech for my tastes (you depend on
printer and screen gamma for readability, and you'll waste extra
toner when pepole print the stuff), but something like "Unreleased
preview -- only use for evaluation" in the foot line I'd like a lot.

I'm grateful for a ivoatex PR to that effect (I'd propose a makefile
target github-preview); otherwise, I promise to implement something
myself RSN.  Poke me if it's not there within two weeks.

**Comment by molinaro-m** [comment]
@gmantele I like the idea of the pre-release preview (won't enter the naming for that).
@msdemlei if a watermark is out of question the foot line idea would be nice.
Can I suggest to enhance the visibility of the version control revision reference, so user's don't get lost among the builds when referencing?

**Comment by gmantele** [comment]
@jd-au and @msdemlei I like the idea of the watermark or alternately of the additional foot line. I am no expert at all in ivoatex (and even worse in LaTeX). So, I think it is preferable that I do not update myself anything in ivoatex....so, if anybody feels more comfortable than me, can he/she do the PR in ivoatex?

I'll wait for the update of ivoatex before using the Makefile's task able to generate the PDF preview before merging this PullRequest.

@molinaro-m What do you mean with :

> Can I suggest to enhance the visibility of the version control revision reference, so user's don't get lost among the builds when referencing?

The PDF preview will always have a unique URL. Do you want the watermark/foot line referencing the corresponding Git commit hash/ID? Or do you mean including the Git commit hash/ID being explicitly written in the GitHub Pre-Release description?

**Comment by molinaro-m** [comment]
@gmantele yes, I'd like to have the commit hash clearly visible to avoid confusion in cross-commenting (outside GitHub at least). ivoatex already reports that hash, I'd like to have it more visible in this preview.

**Comment by gmantele** [comment]
@molinaro-m Something like this: https://github.com/gmantele/ADQL/releases ? _(see end of the pre-release description)_

**Comment by molinaro-m** [comment]
yes, for the web/repo part that's wonderful.

I meant it also for ivoatex to enhance the vicibility of that meta information in the produced pdf. Currently is is like

Version Control
Revision dbce083, 2020-05-13 12:24:43 +0200

maybe bold-facing or enlarging the size of the revision hash would help the reader to remember what s/he's reading or possibly commenting upon. As I said, this should be up to ivoatex, if feasible.

**Comment by msdemlei** [comment]
On Wed, May 13, 2020 at 02:24:17AM -0700, Grégory Mantelet wrote:
> @jd-au and @msdemlei I like the idea of the watermark or alternately of the additional foot line. I am no expert at all in ivoatex (and even worse in LaTeX). So, I think it is preferable that I do not update myself anything in ivoatex....so, if anybody feels more comfortable than me, can he/she do the PR in ivoatex?
> 
> I'll wait for the update of ivoatex before using the Makefile's task able to generate the PDF preview before merging this PullRequest.

So, I looked into the problem and decided that operationally, a
watermark is nicer after all because I can put it in after a normal
build and I don't have to fiddle with, perhaps, ivoatexmeta to tell
LaTeX it's a draft build.

So, there's now https://github.com/ivoa-std/ivoatex/pull/13 that I'd
love see review on.  While you're at it, can I ask you to review the
two other PRs as well?  In particular the LaTeX build fixes are also
mainly for CI, as forcetex in current ivoatex doesn't do what people
think it does.  It will after that.

**Comment by gmantele** [comment]
I have pulled ivoatex and updated the workflow `preview.yml` so now, the generated PDF has the watermark.

_You can checkout the result on my ADQL's fork: https://github.com/gmantele/ADQL/releases/tag/auto-pdf-preview_

**Review by jd-au — APPROVED** [review]
Looks great!

**Pull request merged**
