### PR TITLE
[RFC] DCP suggested modifications

### PR DESCRIPTION
**Pull request by gmantele**
All these commits are modifications suggested by DCP WG during [ADQL-2.1's RFC](https://wiki.ivoa.net/twiki/bin/view/IVOA/ADQL21RFC#Data%20Curation%20%20Preservation%20Inte).

### CODE REVIEW

**Review by msdemlei — COMMENTED** [review]
Ummm... I may entirely be missing what this is intended to do, but I'd read this change as boiling down to "coord_value is a numeric value function", which it definitely is not.

If you want to address Gilles' point about  coord_value missing in this part, you could perhaps say "...where coord_value ::= ...

Me... you know, I think that's a slippery slope.  As you say in your RFC response, if we try to define all the dependent nonterminals, the text will become really terrible.  And since we don't define numeric_value_expression in the running text, I think it'd be totally fair to leave out the rule for coord_value entirely (or just say a half-sentence of prose about it).

**Comment by gmantele** [comment]
I agree with you. I added this definition in here because the paragraph was mentionning the second version of the geometrical function. Knowing that, according to me, it makes sense to explain what parameters roughly are: that's to say a `coord_value` is a pair of coordinates. But I'd definitely not go further than that. This simple addition does not hurt and may be useful for someone that is not familiar with ADQL-2.1 changes and wants to know more about the number and rough category of parameters. But I agree with you, I do not intend to do that for all terms...otherwise it would multiple copy-pastes of the BNF (which is already terrible to maintain).

**Comment by msdemlei** [comment]
On Thu, Apr 27, 2023 at 04:40:20AM -0700, Grégory Mantelet wrote:
> function. Knowing that, according to me, it makes sense to explain
> what parameters roughly are: that's to say a `coord_value` is a
> pair of coordinates. But I'd definitely not go further than that.

Well, I won't stand in your way, but as I said you shouldn't add this
rule to the "and... and... and" concatenation, because that would
imply that coord_value is a numeric_value_function, which it is not.

So, if you want to keep it, just make the "and" in front of the role
a "where" -- that ought to avoid this ambiguity at least for
attentive readers.  And the others won't notice the
numeric_value_function implication in the first place :-)

**Comment by gmantele** [comment]
@msdemlei , is it better like this?

**Review by msdemlei — APPROVED** [review]
Yeah, let's go ahead with this.  Thanks!

**Pull request merged**
