### PR TITLE
Cleaning up the change log

### PR DESCRIPTION
**Pull request by gmantele**
This PR aims to finally clean up the change log section of the ADQL document, accordingly to what was suggested in #64.

### CODE REVIEW

**Review by msdemlei — CHANGES_REQUESTED** [review]
Oh wow – heroic!  Thanks a lot.

However, I'm not so wild about C.2 "ideas for future versions".  Even if it's just a non-normative appendix, this kind of thing IMHO doesn't belong into a standards text.  Let's use
https://wiki.ivoa.net/twiki/bin/view/IVOA/ADQL-2_1-Next for that.

I think you dropped the addition of BLOB and CLOB – was that on purpose?

The old changelog had “Removed restriction on nested JOINs”.  I don't remember what this was, but superficially it sounds as if it still might merit a changelog entry.  If you dropped it on purpose, ignore this comment.

**Comment by gmantele** [comment]
> However, I'm not so wild about C.2 "ideas for future versions". Even if it's just a non-normative appendix, this kind of thing IMHO doesn't belong into a standards text. Let's use
> https://wiki.ivoa.net/twiki/bin/view/IVOA/ADQL-2_1-Next for that.

Ok. Fine with me. Let's remove this section from this document and create this twiki page. I'll do in the coming commit.

-----

> I think you dropped the addition of BLOB and CLOB – was that on purpose?

No panic, it is not dropped from ADQL-2.1 :laughing: Instead of adding one entry for each datatype we added with this 2.1 version (though, none was listed at all in ADQL-2.0), I suggest to have a look at all of them with the entry:

> Description of accepted datatypes and their mapping with VOTable

But you're right, I could anyway briefly list all the implied datatypes in this entry directly. I'll do that in a next commit too.

-----

> The old changelog had “Removed restriction on nested JOINs”. I don't remember what this was, but superficially it sounds as if it still might merit a changelog entry. If you dropped it on purpose, ignore this comment.

I personally don't know either. I had to look up in the Git history: https://github.com/ivoa-std/ADQL/commit/ea6844cf297c7234e1d61b808f9481ef2cb26fb6
It did not appear, to me, as a so important modification to appear in the change log. But if you think so, please, what would you write in very few words to describe it?

**Comment by msdemlei** [comment]
On Wed, Mar 08, 2023 at 03:54:19AM -0800, Grégory Mantelet wrote:
> I personally don't know either. I had to look up in the Git
> history:
> https://github.com/ivoa-std/ADQL/commit/ea6844cf297c7234e1d61b808f9481ef2cb26fb6
> It did not appear, to me, as a so important modification to appear
> in the change log. But if you think so, please, what would you
> write in very few words to describe it?

If you don't consider it worth mentioning, I'm taking your word for
it.  Let's merge!

**Review by msdemlei — DISMISSED** [review]
(as per my mail comments)

**Comment by gmantele** [comment]
After my last commits, is it still ok to merge this Pull-Request?

**Comment by gmantele** [comment]
I just rebased all commits of this Pull-Request on top of those of PR #75, just merged with master.
So, nothing new in there.

**Comment by gmantele** [comment]
Still ok to approve and merge this Pull-Request?

**Comment by msdemlei** [comment]
On Thu, Mar 09, 2023 at 11:54:41PM -0800, Grégory Mantelet wrote:
> Still ok to approve and merge this Pull-Request?

Sure.  In case github has discarded the approval, please just
force-merge...

**Pull request merged**
